name: PushTimeMachineAnalysis

on:
  schedule: 
    - cron: "0 12 * * 0"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install puppeteer
    - run: npm install axios
    - run: npm install echarts
    - name: Setup fonts
      run: |
        sudo apt-get install ttf-mscorefonts-installer
        sudo apt-get install fontconfig
        fc-list :lang=zh
        ls -lh /usr/share/fonts/
        cp -rf ./sources/fonts/* /usr/share/fonts/
        mkfontscale
        mkfontdir
        fc-cache
        echo "#############################################"
        fc-list :lang=zh
    - name: Run code and push image
      env:
        SMMS_TOKEN: ${{ secrets.SMMS_TOKEN }}
        WX_SERVER_TOKEN: ${{ secrets.WX_SERVER_TOKEN }}
        NETEASEMUSIC_COOKIE: ${{ secrets.NETEASEMUSIC_COOKIE }}
      run: node machine.js
